### ISSUE TITLE
Issue 8.3: Enhance Utility Modules Performance

### ISSUE THREAD

**Issue by meirborowski** [meirborowski/ts-grib2-toolkit#31]
### Description

Utility modules, while auxiliary, can significantly impact the overall performance if not optimized, especially if they are frequently used.

#### Tasks:
- [ ] Refactor and optimize utility modules based on profiling results.
- [ ] Implement caching or other optimization techniques where appropriate.
- [ ] Validate the performance improvements with benchmarks.

### Acceptance Criteria

- Utility modules are optimized for maximum efficiency.
- Benchmarks show a tangible performance improvement in these modules.
